### PR TITLE
LocalTarget: Add a 'use_qemu' property.

### PR DESCRIPTION
**Pull request by ltfish**

### CODE REVIEW

**Comment by zardus** [comment]
Can you show me where this is used, in practice? It seems like, for things that need qemu, qemu-mipsel or whatnot would be in the docker image entrypoint itself. We should never have to modify the target like this.

**Comment by rhelmot** [comment]
Realistically, this option should be for "this image needs to run on a host arch other than my native one", but I think that, like, completely undermines the entire implementation of the docker target...

**Comment by zardus** [comment]
Fish and I talked. I'm going to move this to LocalTarget, because like you said, the qemu should be specified in the dockerfile explicitly for docker targets.

**Comment by ltfish** [comment]
Moved!

**Pull request merged**
