### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by ConnorNelson**

### CODE REVIEW

**Comment by rhelmot** [comment]
test_datascout_local is still failing in CI. what's up?

https://dev.azure.com/angr/archr/_build/results?buildId=5020&view=ms.vss-test-web.build-test-results-tab

**Comment by ConnorNelson** [comment]
@twizmwazin How do I easily replicate the test environment? I am currently reverse engineering the CI system. I just want to `docker run -it --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v local/archr:/home/angr/angr-dev/archr angr/angr nosetests -v /home/angr/angr-dev/archr/tests`. If it passes doing that, it should pass on CI. Instead, despite using Docker, it feels like I'm still just stuck in a "works on my machine, wtf" situation.

**Comment by ConnorNelson** [comment]
Wow, https://github.com/angr/ci-settings documents exactly what I want. Nice.

**Comment by twizmwazin** [comment]
@ConnorNelson Here are the instructions to run the CI container: https://github.com/angr/ci-settings#manual-builds. I believe the host is ubuntu 18.04.

**Pull request merged**
